name = "p2p-kids-cf-worker"
main = "src/index.ts"
compatibility_date = "2025-12-30"

# Default deployment (production)
[env.production]
name = "p2p-kids-cf-worker-prod"

# Development deployment (used by CI on non-main branches)
[env.development]
name = "p2p-kids-cf-worker-dev"
