-- ========================================
-- STEP 6: Insert Configuration Values
-- ========================================

INSERT INTO admin_config (key, value, description, category, data_type, is_secret, is_active) VALUES
('subscription_price_monthly', '7.99', 'Monthly subscription price in USD', 'subscription', 'number', FALSE, TRUE),
('subscription_price_yearly', '79.99', 'Annual subscription price in USD (12% discount)', 'subscription', 'number', FALSE, TRUE),
('trial_period_days', '30', 'Trial period duration in days', 'subscription', 'number', FALSE, TRUE),
('trial_enabled', 'true', 'Enable free trial for new subscribers', 'subscription', 'boolean', FALSE, TRUE),
('grace_period_days', '90', 'Grace period after subscription cancellation (SP frozen)', 'subscription', 'number', FALSE, TRUE),
('sp_earn_multiplier', '1.0', 'Multiplier for SP earned per $1 spent by buyer', 'swap_points', 'number', FALSE, TRUE),
('sp_max_percentage_per_purchase', '50', 'Max % of item price payable with SP (0-100)', 'swap_points', 'number', FALSE, TRUE),
('sp_pending_days', '3', 'Days SP stays pending before release (cancelable on return)', 'swap_points', 'number', FALSE, TRUE),
('sp_expiration_days', '90', 'Days until SP expires if inactive', 'swap_points', 'number', FALSE, TRUE),
('sp_min_balance_for_redemption', '100', 'Minimum SP balance required to spend', 'swap_points', 'number', FALSE, TRUE),
('sp_redemption_multiplier', '1.0', 'Exchange rate: 1 SP = X cents in discount', 'swap_points', 'number', FALSE, TRUE),
('sp_subscriber_only', 'true', 'Only Kids Club+ subscribers can earn/spend SP', 'swap_points', 'boolean', FALSE, TRUE),
('platform_fee_buyer_fixed_cents', '25', 'Fixed buyer fee in cents ($0.25)', 'fees', 'number', FALSE, TRUE),
('platform_fee_buyer_percentage', '2.5', 'Buyer fee as % of item price', 'fees', 'number', FALSE, TRUE),
('platform_fee_seller_percentage', '5', 'Seller fee as % of item price', 'fees', 'number', FALSE, TRUE),
('platform_fee_seller_discount_percentage_freemium', '0', 'Seller fee discount for free users (%)', 'fees', 'number', FALSE, TRUE),
('platform_fee_seller_discount_percentage_kids_club_plus', '0', 'Seller fee discount for Kids Club+ (%)', 'fees', 'number', FALSE, TRUE),
('stripe_transaction_fee_percentage', '2.9', 'Stripe transaction fee (%)', 'fees', 'number', FALSE, TRUE),
('stripe_transaction_fee_fixed_cents', '30', 'Stripe transaction fee (fixed cents)', 'fees', 'number', FALSE, TRUE),
('min_transaction_amount_cents', '100', 'Minimum transaction amount in cents ($1.00)', 'fees', 'number', FALSE, TRUE),
('twilio_enabled', 'true', 'Enable SMS verification via Twilio', 'sms', 'boolean', FALSE, TRUE),
('sms_verification_timeout_minutes', '10', 'SMS verification code expiration in minutes', 'sms', 'number', FALSE, TRUE),
('sms_daily_limit_per_user', '5', 'Max SMS verification attempts per user per day', 'sms', 'number', FALSE, TRUE),
('sendgrid_enabled', 'true', 'Enable transactional emails via SendGrid', 'email', 'boolean', FALSE, TRUE),
('email_from_address', 'noreply@kidsp2p.com', 'Sender email address for transactional emails', 'email', 'string', FALSE, TRUE),
('moderation_ai_enabled', 'true', 'Enable AI content moderation', 'moderation', 'boolean', FALSE, TRUE),
('moderation_human_review_threshold', 'medium', 'Trigger human review for: low/medium/high risk items', 'moderation', 'string', FALSE, TRUE),
('moderation_auto_reject_high_risk', 'false', 'Auto-reject high-risk items without review', 'moderation', 'boolean', FALSE, TRUE),
('cpsc_recall_check_enabled', 'true', 'Enable CPSC product recall checking', 'safety', 'boolean', FALSE, TRUE),
('prohibited_items_check_enabled', 'true', 'Enable prohibited items list checking', 'safety', 'boolean', FALSE, TRUE),
('firebase_analytics_enabled', 'true', 'Enable Firebase analytics event tracking', 'analytics', 'boolean', FALSE, TRUE),
('analytics_user_session_tracking', 'true', 'Track detailed user session analytics', 'analytics', 'boolean', FALSE, TRUE),
('feature_flag_sp_redemption_enabled', 'true', 'Enable Swap Points redemption feature', 'feature_flags', 'boolean', FALSE, TRUE),
('feature_flag_referral_program_enabled', 'false', 'Enable referral program (future feature)', 'feature_flags', 'boolean', FALSE, TRUE),
('feature_flag_bundle_purchases_enabled', 'false', 'Enable purchasing multiple items at once', 'feature_flags', 'boolean', FALSE, TRUE);
