-- filepath: supabase/migrations/063_fix_trades_fk.sql

-- Mode B: Idempotent rerunnable migration
-- Fix trades table foreign keys to reference auth.users instead of public.users.
-- This ensures that trades can be created even if the public.users table is not populated.

DO $$
BEGIN
    -- 1. Drop existing foreign key constraints if they exist
    -- These might be named differently depending on how they were created, 
    -- so we check the constraint names.
    
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_trades_buyer_id') THEN
        ALTER TABLE trades DROP CONSTRAINT fk_trades_buyer_id;
    END IF;

    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_trades_seller_id') THEN
        ALTER TABLE trades DROP CONSTRAINT fk_trades_seller_id;
    END IF;

    -- Also check for default names generated by Postgres/Supabase
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'trades_buyer_id_fkey') THEN
        ALTER TABLE trades DROP CONSTRAINT trades_buyer_id_fkey;
    END IF;

    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'trades_seller_id_fkey') THEN
        ALTER TABLE trades DROP CONSTRAINT trades_seller_id_fkey;
    END IF;
END $$;

-- 2. Add new foreign key constraints referencing auth.users(id)
ALTER TABLE trades
  ADD CONSTRAINT fk_trades_buyer_id 
  FOREIGN KEY (buyer_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE trades
  ADD CONSTRAINT fk_trades_seller_id 
  FOREIGN KEY (seller_id) REFERENCES auth.users(id) ON DELETE CASCADE;

-- 3. Ensure listing_id also references items(id) correctly
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'trades_listing_id_fkey') THEN
        ALTER TABLE trades DROP CONSTRAINT trades_listing_id_fkey;
    END IF;
END $$;

ALTER TABLE trades
  ADD CONSTRAINT fk_trades_listing_id 
  FOREIGN KEY (listing_id) REFERENCES items(id) ON DELETE CASCADE;
