// File: p2p-kids-marketplace/src/types/profile.types.ts
// Profile-related type definitions for AUTH-005, AUTH-006
// NOTE: The full `Database` types are generated by Supabase tooling.
// To keep the codebase type-checkable in CI without the generated file,
// provide minimal local fallback types here. Replace with generated
// types when available.

export type User = {
  id: string;
  email?: string | null;
  created_at?: string | null;
  metadata?: Record<string, any> | null;
  display_name?: string | null;
  name?: string | null;
  avatar_url?: string | null;
  phone?: string | null;
  node_id?: string | null;
};

export type UserInsert = Partial<User> & { email?: string };
export type UserUpdate = Partial<User>;

export type Node = {
  id: string;
  name?: string | null;
  zip_codes?: string[] | null;
};

export interface ProfileSetupData {
  display_name: string;
  avatar_url?: string;
  zip_code: string;
  bio?: string;
  email?: string;
  phone?: string;
}

export interface ProfileUpdateData {
  display_name?: string;
  avatar_url?: string;
  zip_code?: string;
  bio?: string;
  phone?: string;
}

export interface UploadAvatarResult {
  url: string | null;
  path?: string | null;
  error: Error | object | null;
}

export interface NodeAssignment {
  node_id: string;
  node_name: string;
  distance_miles?: number;
  is_exact_match?: boolean; // NODE-003: true if exact ZIP match, false if fallback/nearest
}
